config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", confirmations: "users/confirmations", registrations: "users/registrations", passwords: "users/passwords", unlocks: "users/unlocks",  }
  root(to: "pages#index")
  get("/admin", to: "admin/pages#index")
  resources :orders

  namespace :admin do
  	resources :deliveries
  	resources :supplies
    resources :products
  	resources :orders
    get("/users/resolve/:id", to: "users#resolve_new", as: "user_resolve")
    get("/users/sign_up", to: "users#sign_up", as: "user_sign_up")
    get("/orders/up/:id", to: "orders#move_status_up", as: "order_status_up")
    get("/orders/down/:id", to: "orders#move_status_down", as: "order_status_down")
    get("/orders/cancel/:id", to: "orders#cancel_order", as: "order_status_cancel")
    get("/users/block/:id", to: "users#block", as: "user_block")
    get("/users/resolve_unregistered/:id", to: "users#resolve_new_unregistered", as: "user_resolve_unregistered")
  	get("/users", to: "users#index")
  end
end

app/views/admin/deliveries.html.erb
<!-- Admin CSS -->
<%= render partial: "shared/admin_css" %>
<!-- HEADER -->
<%= render partial: "shared/admin_navbar" %>
<!-- /HEADER -->
<!-- start: Content -->
					<div id="content" class="span10">
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="index.html">Home</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li><a href="#">Deliveries</a></li>
						</ul>
						
						<div class="row-fluid sortable">	
							<div class="box-content">
								<table class="table table-striped table-bordered bootstrap-datatable datatable">
									<thead>
										<tr>
											<th>ID</th>
											<th>Date Delivered</th>
											<th>First Name</th>
											<th>Last Name</th>
											<th>Phone No.</th>
											<th>Billing Address</th>
											<th>Delivery Address</th>
											<th>Orders</th>
											<th>Amount</th>
										</tr>
									</thead>  
									<tbody>
									<% @deliveries.each do |d| %> 
										<% @order = Order.where('delivery_id = ?', d.id).first %>
										<% if !@order.nil? %>
											<% @user = User.where('id = ?', @order.user_id).first %>
											<% if !@user.nil? %>
												<tr>
													<td class="center" scope="row"><%= d.id %></td>
													<td><%= d.created_at %><td>
													<td><%= @user.first_name %></td>
													<td><%= @user.last_name %></td>
													<td><%= @user.phone_number %></td>
													<td><%= @order.delivery_unit_number %> <%= @order.delivery_building %>, <%= @order.delivery_street %>, <%= @order.delivery_village %>, <%= @order.delivery_city %></td>
													<td><%= @order.billing_unit_number %> <%= @order.billing_building %>, <%= @order.billing_street %>, <%= @order.billing_village %>, <%= @order.billing_city %></td>
													<% @orderlines = OrderLine.where('id = ?', @order.id).all %>
													<td>
													<% if !@orderlines.nil? %>
														<% @orderlines.each do |o| %> 
															<% @product = Product.where('id = ?', @orderlines.product_id).first %>
															<% if !@product.nil? %>
																<%= o.quantity %>KG <%= @product.product_name %> <br>
															<% end %>
														<% end %>
													<% end %>
													</td>
													<td>PHP <%= @order.amount_due %></td>
												</tr>
											<% end %>
										<% end %>
									<% end %>
								</tbody>
							</table>         
						</div><!--/span-->
					</div>

				</div>		

				<!-- end: Content -->
			</div><!--/#content.span10-->
		</div><!--/fluid-row-->

		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>

		<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-content">
				<ul class="list-inline item-details">
					<li><a href="http://themifycloud.com">Admin templates</a></li>
					<li><a href="http://themescloud.org">Bootstrap themes</a></li>
				</ul>
			</div>
		</div>

		<div class="clearfix"></div>

	

<!-- FOOTER -->
<%= render partial: "shared/admin_footer" %>
<!-- /FOOTER -->


<!-- Admin Scripts -->
<%= javascript_include_tag 'sorttable' %>
<%= render partial: "shared/admin_javascript" %>

app/views/admin/orders.html.erb
<!-- Admin CSS -->
<%= render partial: "shared/admin_css" %>
<!-- HEADER -->
<%= render partial: "shared/admin_navbar" %>
<!-- /HEADER -->
<!-- start: Content -->
<!-- start: Content -->
		<div id="content" class="span10">
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="index.html">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">Orders</a></li>
			</ul>
			
			<div class="row-fluid">
				<button type="button" class="btn btn-info">New Order</button>
				<br><br>

				<div class="col-md-6">
					<!-- Nav tabs --><div class="card">
					<ul class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active"><a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Pending</a></li>
						<li role="presentation"><a href="#accepted" aria-controls="accepted" role="tab" data-toggle="tab">Accepted</a></li>
						<li role="presentation"><a href="#processing" aria-controls="processing" role="tab" data-toggle="tab">Processing</a></li>
						<li role="presentation"><a href="#dispatched" aria-controls="dispatched" role="tab" data-toggle="tab">Dispatched</a></li>
						<li role="presentation"><a href="#delivered" aria-controls="delivered" role="tab" data-toggle="tab">Delivered</a></li>
						<li role="presentation"><a href="#cancelled" aria-controls="cancelled" role="tab" data-toggle="tab">Cancelled</a></li>
					</ul>

					<!-- Tab panes -->
					<div class="tab-content">
						<div role="tabpanel" class="tab-pane active" id="pending">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Pending' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
												<td><span class="label label-success"><%= link_to "Move Status Up", admin_order_status_up_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-danger"><%= link_to "Cancel Order", admin_order_status_cancel_path(o.id), {:style=>'color:#fff;'} %></span></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>

						<div role="tabpanel" class="tab-pane" id="accepted">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Accepted' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
												<td><span class="label label-important"><%= link_to "Move Status Down", admin_order_status_down_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-success"><%= link_to "Move Status Up", admin_order_status_up_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-danger"><%= link_to "Cancel Order", admin_order_status_cancel_path(o.id), {:style=>'color:#fff;'} %></span></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>

						<div role="tabpanel" class="tab-pane" id="processing">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Processing' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
												<td><span class="label label-important"><%= link_to "Move Status Down", admin_order_status_down_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-success"><%= link_to "Move Status Up", admin_order_status_up_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-danger"><%= link_to "Cancel Order", admin_order_status_cancel_path(o.id), {:style=>'color:#fff;'} %></span></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>

						<div role="tabpanel" class="tab-pane" id="dispatched">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Dispatched' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
												<td><span class="label label-important"><%= link_to "Move Status Down", admin_order_status_down_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-success"><%= link_to "Move Status Up", admin_order_status_up_path(o.id), {:style=>'color:#fff;'} %> </span><span class="label label-danger"><%= link_to "Cancel Order", admin_order_status_cancel_path(o.id), {:style=>'color:#fff;'} %></span></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>

						<div role="tabpanel" class="tab-pane" id="delivered">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Delivered' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>

						<div role="tabpanel" class="tab-pane" id="cancelled">
							<table class="table table-striped bootstrap-datatable datatable">
								<thead>
									<tr>
										<th>id</th>
										<th>Date Ordered</th>
										<th>First Name</th>
										<th>Last Name</th>
										<th>Phone No.</th>
										<th>Email Address</th>
									</tr>
								</thead>
								<tbody>
									<% @orders.each do |o| %>
										<% if o.status == 'Cancelled' %>
											<% @users = User.find_by_id(o.user_id) %>
											<tr>
												<td scope="row"><%= o.id %></td>
												<td><%= o.date_ordered %></td>
												<td><%= @users.first_name %></td>
												<td><%= @users.last_name %></td>
												<td><%= @users.phone_number %></td>
												<td><%= @users.email %></td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<br>	

			<!-- end: Content -->
		</div><!--/#content.span10-->
	</div><!--/fluid-row-->

	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Settings</h3>
		</div>
		<div class="modal-body">
			<p>Here settings can be configured...</p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Close</a>
			<a href="#" class="btn btn-primary">Save changes</a>
		</div>
	</div>

	<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
			<ul class="list-inline item-details">
				<li><a href="http://themifycloud.com">Admin templates</a></li>
				<li><a href="http://themescloud.org">Bootstrap themes</a></li>
			</ul>
		</div>
	</div>

	<div class="clearfix"></div>

	

<!-- FOOTER -->
<%= render partial: "shared/admin_footer" %>
<!-- /FOOTER -->


<!-- Admin Scripts -->
<%= render partial: "shared/admin_javascript" %>

app/views/admin/sign_up.html.erb
<!-- Admin CSS -->
<%= render partial: "shared/admin_css" %>
<!-- HEADER -->
<%= render partial: "shared/admin_navbar" %>

<h2>Sign up</h2>

<%= simple_form_for @users do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.input :first_name, required: true %>
    <%= f.input :last_name, required: true %>
    <%= f.input :phone_number, required: true %>
    <%= f.hidden_field :account_type, :value => "a" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<!-- FOOTER -->
<%= render partial: "shared/admin_footer" %>
<!-- /FOOTER -->


<!-- Admin Scripts -->
<%= render partial: "shared/admin_javascript" %>

app/views/admin/supplies.html.erb
<!-- Admin CSS -->
<%= render partial: "shared/admin_css" %>
<!-- HEADER -->
<%= render partial: "shared/admin_navbar" %>
<!-- /HEADER -->
<!-- start: Content -->
<!-- start: Content -->
					<div id="content" class="span10">
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="index.html">Home</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li><a href="#">Supply and Product</a></li>
						</ul>

						<div class="col-md-12">
							<div class="col-md-5">
								<div class="row-fluid">
									<center>
									<%= link_to "New Product", admin_order_status_up_path(o.id), {:style=>'color:#fff;'} %><a href="new product.html" class="btn btn-info">New Product</a>
								</center>
									<br>
									<ul class="thumbnails">
									<% @products.each do |p| %>
										<li class="span4">
											<div class="thumbnail">
											<% if p.product_name == 'Blueberry' %>
												<%= image_tag 'prod-blueberry.jpg' %>
											<% elsif p.product_name == 'Cherry' %>
												<%= image_tag 'prod-cherries.jpg' %>
											<% elsif p.product_name == 'Grapefruit' %>
												<%= image_tag 'prod-grapefruit.jpg' %>
											<% elsif p.product_name == 'Kale' %>
												<%= image_tag 'prod-kale.jpg' %>
											<% elsif p.product_name == 'Lemon' %>
												<%= image_tag 'prod-lemon.jpg' %>
											<% elsif p.product_name == 'Lychee' %>
												<%= image_tag 'prod-lychee.jpg' %>
											<% elsif p.product_name == 'Strawberry' %>
												<%= image_tag 'prod-strawberry.jpg' %>
											<% end %>
												<div class="caption">
													<center>
														<h3><%= p.product_name %></h3>
														<% @supply = Supply.where('product_id = ?', p.id).last %> | ₱<%= p.price %>
														<% if !@supply.nil? %>
														<p><%= @supply.quantity %> | ₱<%= p.price %>/kg</p>
														<% else %>
														<p>0 | ₱<%= p.price %>/kg</p>
														<% end %>
														<%= link_to(edit_admin_product_path(p.id)) do %><i class="icon-pencil"></i><% end %>
														<%= link_to('/admin/orders/(p.id)', :method => :delete) do %><i class="icon-remove"></i><% end %>
													</center>
												</div>
											</div>
										</li>
									<% end %>
									</ul>
									<center>
										<a href="add supply.html" class="btn btn-success" style="margin-right: 5px;"><i class="icon-plus"> Add Supply</i></a>
										<a href="reduce supply.html" class="btn btn-danger"><i class="icon-minus"> Reduce Supply</i></a>
									</center>
								</div>	
							</div>	


							<div class="col-md-6">
								<div class="row-fluid">
									<div class="tab-content">
										<table class="table table-striped bootstrap-datatable datatable">
											<thead>
												<tr>
													<th>#</th>
													<th>Date Replenished</th>
													<th>Product</th>
													<th>+</th>
													<th>-</th>
													<th>Admin</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td scope="row">1</td>
													<td>2/22/17</td>
													<td>Kale
														<br>
														Blueberry
													</td>
													<td>2 kg
														<br>
														1.5 kg
													</td>
													<td>1 kg
													</td>
													<td>Chuck Eh</td>
												</tr>
												<tr>
													<td scope="row">2</td>
													<td>2/23/17</td>
													<td>Strawberry</td>
													<td>5 kg</td>
													<td></td>
													<td>Chuck Eh</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>

						<div class="modal hide fade" id="myModal">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">×</button>
								<h3>Settings</h3>
							</div>
							<div class="modal-body">
								<p>Here settings can be configured...</p>
							</div>
							<div class="modal-footer">
								<a href="#" class="btn" data-dismiss="modal">Close</a>
								<a href="#" class="btn btn-primary">Save changes</a>
							</div>
						</div>

						<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
							<div class="modal-content">
								<ul class="list-inline item-details">
									<li><a href="http://themifycloud.com">Admin templates</a></li>
									<li><a href="http://themescloud.org">Bootstrap themes</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix"></div>

	

<!-- FOOTER -->
<%= render partial: "shared/admin_footer" %>
<!-- /FOOTER -->


<!-- Admin Scripts -->
<%= render partial: "shared/admin_javascript" %>

app/views/admin/users.html.erb
<!-- Admin CSS -->
<%= render partial: "shared/admin_css" %>
<!-- HEADER -->
<%= render partial: "shared/admin_navbar" %>
<!-- /HEADER -->
<!-- start: Content -->
<!-- start: Content -->
					<div id="content" class="span10">
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="index.html">Home</a> 
								<i class="icon-angle-right"></i>
							</li>
							<li><a href="#">Customer Accounts</a></li>
						</ul>
						
						<div class="row-fluid">
							<span class="label label-success"><%= link_to "Create New Admin Account", admin_user_sign_up_path, {:style=>'color:#fff;'} %> </span>
							<br><br>

								<!-- Nav tabs --><div class="card">
								<ul class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="#registered" aria-controls="registered" role="tab" data-toggle="tab">Registered</a></li>
									<li role="presentation"><a href="#unregistered" aria-controls="unregistered" role="tab" data-toggle="tab">Unregistered</a></li>
									<li role="presentation"><a href="#administration" aria-controls="administration" role="tab" data-toggle="tab">Administration</a></li>
								</ul>

								<!-- Tab panes -->
								<div class="tab-content">
									<div role="tabpanel" class="tab-pane active" id="registered">
										<table class="table table-striped bootstrap-datatable datatable">
											<thead>
												<tr>
													<th>#</th>
													<th>Date Registered</th>
													<th>Name</th>
													<th>Total Transactions</th>
													<th>Outstanding Bal.</th>
													<th>Phone No.</th>
													<th>Email Address</th>
													<th>Access</th>
												</tr>
											</thead>
											<tbody>
											<% @users.each do |u| %>
												<tr>
													<td scope="row"><%= u.id %></td>
													<td><%= u.created_at %></td>
													<td><a href="order history.html"><%= u.first_name %> <%= u.last_name %></a></td>
													<td><%= Order.where('id = ?', u.id).count %></td>
													<% if u.outstanding_balance.nil? == false and u.outstanding_balance > 1%>
														<td><span class="label label-important">PHP <%= u.outstanding_balance %></span><span class="label label-success"><%= link_to "Resolve", admin_user_resolve_path(u.id), {:style=>'color:#fff;'} %></span></td>
													<% else %>
														<td></td>
													<% end %>
													<td><%= u.phone_number %></td>
													<td><%= u.email %></td>
													<% if !u.blocked? %>
													<td><span class="label label-important"><%= link_to "Block", admin_user_block_path(u.id) %></span></td>
													<% else %>
													<td><span class="label label-success"><%= link_to "Unblock", admin_user_block_path(u.id), {:style=>'color:#fff;'} %></span></td>
													<% end %>
												</tr>
											<% end %>
											</tbody>
										</table>
								</div>

								<div role="tabpanel" class="tab-pane" id="unregistered">
									<table class="table table-striped bootstrap-datatable datatable">
											<thead>
													<th>#</th>
													<th>Date Registered</th>
													<th>Name</th>
													<th>Total Transactions</th>
													<th>Outstanding Bal.</th>
													<th>Phone No.</th>
												</tr>
											</thead>
											<% @accounts.each do |u| %>
												<tr>
													<td scope="row"><%= u.id %></td>
													<td><%= u.created_at %></td>
													<td><a href="order history.html"><%= u.first_name %> <%= u.last_name %></a></td>
													<td><%= Order.where('id = ?', u.id).count %></td>
													<% if u.outstanding_balance.nil? == false and u.outstanding_balance > 1%>
														<td><span class="label label-important">PHP <%= u.outstanding_balance %></span><span class="label label-success"><%= link_to "Resolve", admin_user_resolve_unregistered_path(u.id), {:style=>'color:#fff;'} %></span></td>
													<% else %>
														<td></td>
													<% end %>
													<td><%= u.phone_number %></td>
												</tr>
											<% end %>
											</tbody>
										</table>
								</div>

								<div role="tabpanel" class="tab-pane" id="administration">
									<table class="table table-striped bootstrap-datatable datatable">
											<thead>
												<tr>
													<th>#</th>
													<th>Date Registered</th>
													<th>Name</th>
													<th>Phone No.</th>
													<th>Email Address</th>
												</tr>
											</thead>
											<tbody>
											<% @users.each do |u| %>
												<% if u.account_type == 'a' %>
												<tr>
													<td scope="row"><%= u.id %></td>
													<td><%= u.created_at %></td>
													<td><a href="order history.html"><%= u.first_name %> <%= u.last_name %></a></td>
													<td><%= u.phone_number %></td>
													<td><%= u.email %></td>
												</tr>
												<% end %>
											<% end %>
											</tbody>
										</table>
								</div>
							</div>
						</div>

					<br>
					<center>
				</center>
				</div>		

				<!-- end: Content -->
			</div><!--/#content.span10-->
		</div><!--/fluid-row-->

		<div class="modal hide fade" id="myModal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Settings</h3>
			</div>
			<div class="modal-body">
				<p>Here settings can be configured...</p>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn" data-dismiss="modal">Close</a>
				<a href="#" class="btn btn-primary">Save changes</a>
			</div>
		</div>

		<div class="common-modal modal fade" id="common-Modal1" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-content">
				<ul class="list-inline item-details">
					<li><a href="http://themifycloud.com">Admin templates</a></li>
					<li><a href="http://themescloud.org">Bootstrap themes</a></li>
				</ul>
			</div>
		</div>

		<div class="clearfix"></div>

	

<!-- FOOTER -->
<%= render partial: "shared/admin_footer" %>
<!-- /FOOTER -->


<!-- Admin Scripts -->
<%= render partial: "shared/admin_javascript" %>