config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", confirmations: "users/confirmations", registrations: "users/registrations", passwords: "users/passwords", unlocks: "users/unlocks",  }
  root(to: "pages#index")
  get("/admin", to: "admin/pages#index")
  resources :orders

  namespace :admin do
  	resources :deliveries
  	resources :supplies
    resources :products
  	resources :orders
    get("/users/resolve/:id", to: "users#resolve_new", as: "user_resolve")
    get("/users/sign_up", to: "users#sign_up", as: "user_sign_up")
    get("/orders/up/:id", to: "orders#move_status_up", as: "order_status_up")
    get("/orders/down/:id", to: "orders#move_status_down", as: "order_status_down")
    get("/orders/cancel/:id", to: "orders#cancel_order", as: "order_status_cancel")
    get("/users/block/:id", to: "users#block", as: "user_block")
    get("/users/resolve_unregistered/:id", to: "users#resolve_new_unregistered", as: "user_resolve_unregistered")
  	get("/users", to: "users#index")
  end
end

app/views/shared/_admin_css.html.erb
<%= stylesheet_link_tag    'bootstrap-admin', media: "all", id: "bootstrap-style" %>
<%= stylesheet_link_tag    'bootstrap-responsive', media: "all" %>
<%= stylesheet_link_tag    'style', media: "all", id: "base-style" %>
<%= stylesheet_link_tag    'style-responsive', media: "all", id: "base-style-responsive" %>
<%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' %>

<%= stylesheet_link_tag    'jquery-ui-1.8.21.custom', media: "all" %>
<%= stylesheet_link_tag    'fullcalendar', media: "all" %>
<%= stylesheet_link_tag    'chosen', media: "all" %>
<%= stylesheet_link_tag    'uniform.default', media: "all" %>
<%= stylesheet_link_tag    'jquery.cleditor', media: "all" %>
<%= stylesheet_link_tag    'jquery.noty', media: "all" %>
<%= stylesheet_link_tag    'noty_theme_default', media: "all" %>
<%= stylesheet_link_tag    'elfinder.min', media: "all" %>
<%= stylesheet_link_tag    'elfinder.theme', media: "all" %>
<%= stylesheet_link_tag    'jquery.iphone.toggle', media: "all" %>
<%= stylesheet_link_tag    'uploadify', media: "all" %>
<%= stylesheet_link_tag    'jquery.gritter', media: "all" %>
<%= stylesheet_link_tag    'font-awesome.min', media: "all" %>
<%= stylesheet_link_tag    'font-awesome-ie7.min', media: "all" %>
<%= stylesheet_link_tag    'glyphicons', media: "all" %>
<%= stylesheet_link_tag    'halflings', media: "all" %>
<%= stylesheet_link_tag    'style-forms', media: "all" %>

app/views/shared/_admin_footer.html.erb
<footer>

	<p>
		<span style="text-align:right;float:right">&copy; Created by Team Pura (MIS 122 Project) SY 2016-2017</a></span>
		
	</p>

</footer>

<!-- start: JavaScript-->

		
	<!-- end: JavaScript-->

app/views/shared/_admin_javascript.html.erb
<%= javascript_include_tag 'jquery-1.9.1.min' %>
<%= javascript_include_tag 'jquery-migrate-1.0.0.min' %>

<%= javascript_include_tag 'jquery-ui-1.10.0.custom.min' %>

<%= javascript_include_tag 'jquery.ui.touch-punch' %>

<%= javascript_include_tag 'modernizr' %>

<%= javascript_include_tag 'bootstrap.min' %>

<%= javascript_include_tag 'jquery.cookie' %>

<%= javascript_include_tag 'fullcalendar.min' %>

<%= javascript_include_tag 'jquery.dataTables.min' %>

<%= javascript_include_tag 'excanvas' %>
<%= javascript_include_tag 'jquery.flot' %>
<%= javascript_include_tag 'jquery.flot.pie' %>
<%= javascript_include_tag 'jquery.flot.stack' %>
<%= javascript_include_tag 'jquery.flot.resize.min' %>

<%= javascript_include_tag 'jquery.chosen.min' %>

<%= javascript_include_tag 'jquery.uniform.min' %>

<%= javascript_include_tag 'jquery.cleditor.min' %>

<%= javascript_include_tag 'jquery.noty' %>

<%= javascript_include_tag 'jquery.elfinder.min' %>

<%= javascript_include_tag 'jquery.raty.min' %>

<%= javascript_include_tag 'jquery.iphone.toggle' %>

<%= javascript_include_tag 'jquery.uploadify-3.1.min' %>

<%= javascript_include_tag 'jquery.gritter.min' %>

<%= javascript_include_tag 'jquery.imagesloaded' %>

<%= javascript_include_tag 'jquery.masonry.min' %>

<%= javascript_include_tag 'jquery.knob.modified' %>

<%= javascript_include_tag 'jquery.sparkline.min' %>

<%= javascript_include_tag 'counter' %>

<%= javascript_include_tag 'retina' %>

<%= javascript_include_tag 'custom' %>

app/views/shared/_admin_navbar.html.erb
<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to(admin_path, { :class=>"brand" }) do %><span>Crate2Plate</span><% end %></a>
								
				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-bell"></i>
								<span class="badge red">
								7 </span>
							</a>
							<ul class="dropdown-menu notifications">
								<li class="dropdown-menu-title">
 									<span>You have 11 notifications</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>	
                            	<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">1 min</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">7 min</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">8 min</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">16 min</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">36 min</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon yellow"><i class="icon-shopping-cart"></i></span>
										<span class="message">2 items sold</span>
										<span class="time">1 hour</span> 
                                    </a>
                                </li>
								<li class="warning">
                                    <a href="#">
										<span class="icon red"><i class="icon-user"></i></span>
										<span class="message">User deleted account</span>
										<span class="time">2 hour</span> 
                                    </a>
                                </li>
								<li class="warning">
                                    <a href="#">
										<span class="icon red"><i class="icon-shopping-cart"></i></span>
										<span class="message">New comment</span>
										<span class="time">6 hour</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">yesterday</span> 
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">yesterday</span> 
                                    </a>
                                </li>
                                <li class="dropdown-menu-sub-footer">
                            		<a>View all notifications</a>
								</li>	
							</ul>
						</li>

						<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white user"></i> Hello, Admin <%= current_user.first_name %>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li class="dropdown-menu-title">
 									<span>Account Settings</span>
								</li>
								<li><a href="#"><i class="halflings-icon user"></i> Profile</a></li>
								<li><%= link_to(destroy_user_session_path, :method => :delete) do %><i class="halflings-icon off"></i> Logout<% end %></li>
							</ul>
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->
				
			</div>
		</div>
	</div>
	<!-- start: Header -->
	
		<div class="container-fluid-full">
		<div class="row-fluid">
				
			<!-- start: Main Menu -->
					<div id="sidebar-left" class="span2">
						<div class="nav-collapse sidebar-nav" data-no-turbolink>
							<ul class="nav nav-tabs nav-stacked main-menu">
								<li><a href="<%= admin_path %>"><i class="icon-bar-chart"></i><span class="hidden-tablet"> <%= params[:controller] %></span></a></li>
								<li><a href="<%= admin_supplies_path %>"><i class="icon-indent-right"></i><span class="hidden-tablet"> Supply and Product</span></a></li>
								<li><a href="<%= admin_users_path %>"><i class="icon-user"></i><span class="hidden-tablet"> Customer Accounts</span></a></li>
								<li><a href="<%= admin_deliveries_path %>"><i class="icon-truck"></i><span class="hidden-tablet"> Deliveries</span></a></li>
								<li><a href="<%= admin_orders_path %>"><i class="icon-list"></i><span class="hidden-tablet"> Orders</span></a></li>
							</ul>
						</div>
					</div>
					<!-- end: Main Menu -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>

app/views/shared/_customer_css.html.erb
<%= stylesheet_link_tag    'bootstrap', media: "all" %>
<%= stylesheet_link_tag    'font-awesome', media: "all" %>
<%= stylesheet_link_tag    'owl.carousel', media: "all" %>
<%= stylesheet_link_tag    'magnific-popup', media: "all" %>
<%= stylesheet_link_tag    'style-lul', media: "all" %>
<%= stylesheet_link_tag    'responsive', media: "all" %>

app/views/shared/_customer_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="row">
			<!-- SOCIAL ICONS -->
			<div class="col-sm-6 col-sm-push-6 footer-social-icons">
				<span>Get in touch with us!</span>
				<a href=""><i class="fa fa-envelope-o"></i></a>
				<a href=""><i class="fa fa-mobile"></i></a>
			</div>
			<!-- /SOCIAL ICONS -->
			<div class="col-sm-6 col-sm-pull-6 copyright">
				<p>&copy; 2016 Crate2Plate</p>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_customer_javascript.html.erb
<!-- jQuery -->
<%= javascript_include_tag 'jquery.min' %>
<!-- Bootstrap -->
<%= javascript_include_tag 'bootstrap-admin.min' %>
<!-- Parallax -->
<%= javascript_include_tag 'jquery.parallax' %>
<!-- Smooth Scroll -->
<%= javascript_include_tag 'smoothscroll' %>
<!-- masonry -->
<%= javascript_include_tag 'masonry.pkgd.min' %>
<!-- fitvids -->
<%= javascript_include_tag 'jquery.fitvids' %>
<!-- Owl-Carousel -->
<%= javascript_include_tag 'owl.carousel.min' %>
<!-- CounterUp -->
<%= javascript_include_tag 'jquery.counterup.min' %>
<!-- CounterUp -->
<%= javascript_include_tag 'waypoints.min' %>
<!-- isotope -->
<%= javascript_include_tag 'jquery.isotope.min' %>
<!-- magnific-popup -->
<%= javascript_include_tag 'jquery.magnific-popup.min' %>
<!-- Scripts -->
<%= javascript_include_tag 'scripts' %>

app/views/shared/_customer_navbar.html.erb
<header id="header">
	<nav class="navbar st-navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#st-navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="logo" href="index.html"><%= image_tag 'web-logo.png', :style => "width: 30%" %><!-- <img src="images/web-logo.png" width="30%" alt=""> --></a>
			</div>

			<div class="collapse navbar-collapse" id="st-navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#header">Order</a></li>
					<li><a href="#services">About Us</a></li>
					<li><a href="#our-works">FAQ</a></li>
					<li><a href="#pricing">Contact Us</a></li>
					<% if user_signed_in? %>
					<li><a href="">Hello, <%= current_user.email %>. </a><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
					<% else %>
					<li><%= link_to "Log in", new_user_session_path %></li>
					<% end %>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container -->
	</nav>
</header>